DROP DATABASE IF EXISTS userdb;
CREATE DATABASE `userdb` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE userdb;

CREATE TABLE IF NOT EXISTS `userdb`.`User` (
 `UserID` INT NOT NULL COMMENT '',
 `LocationName` VARCHAR(45) NULL COMMENT '',
 `LocationAddress` VARCHAR(45) NULL COMMENT '',
 PRIMARY KEY (`UserID`)  COMMENT '')
ENGINE = InnoDB;